"""Tests for the ODA emitter (oda_data.json builder)."""

from __future__ import annotations

import json
from pathlib import Path

from tmf_spec_parser import __version__
from tmf_spec_parser.oda_emitter import build, write_js_module, write_json
from tmf_spec_parser.oda_extractor import APIRef, Component


def _sample_components() -> list[Component]:
    return [
        Component(
            id="TMFC008",
            name="ServiceInventory",
            version="1.2.0",
            functional_block="Production",
            status="specified",
            publication_date="2024-11-12",
            description="Service Inventory.",
            crd_version="v1",
            exposed_apis=[
                APIRef(id="TMF638", name="svc-inv", version="v4.0.0", required=True),
            ],
            dependent_apis=[
                APIRef(id="TMF633", name="svc-cat", version="v4.0.0", required=True),
                APIRef(id="TMF641", name="svc-ord", version="v4.0.0", required=False),
            ],
        ),
        Component(
            id="TMFC001",
            name="ProductCatalogManagement",
            version="2.1.0",
            functional_block="CoreCommerce",
            status="specified",
            publication_date="2024-11-12",
            description="Product Catalog.",
            crd_version="v1",
            exposed_apis=[
                APIRef(id="TMF620", name="prod-cat", version="v4.1.0", required=True),
            ],
            dependent_apis=[
                APIRef(id="TMF632", name="party", version="v4.0.0", required=False),
            ],
        ),
    ]


def test_build_includes_top_level_keys() -> None:
    data = build(_sample_components())
    for key in ("generated_at", "parser_version", "spec_source",
                "components", "links", "stats"):
        assert key in data


def test_build_uses_current_version_string() -> None:
    data = build(_sample_components())
    assert data["parser_version"] == __version__


def test_build_spec_source_points_at_oda_repo() -> None:
    data = build(_sample_components())
    assert "tmforum-rand" in data["spec_source"]
    assert "TMForum-ODA-Ready-for-publication" in data["spec_source"]


def test_build_components_count_matches_input() -> None:
    components = _sample_components()
    data = build(components)
    assert len(data["components"]) == len(components)


def test_build_links_match_dependent_apis() -> None:
    data = build(_sample_components())
    # 2 dependents from TMFC008 + 1 from TMFC001 = 3 links total.
    assert len(data["links"]) == 3
    sources = {link["source"] for link in data["links"]}
    assert sources == {"TMFC008", "TMFC001"}


def test_build_stats_apis_outside_tmf_map_uses_real_known_set() -> None:
    """The emitter uses the canonical 16-API set from config.API_IDS.
    All five APIs in the fixtures (TMF620/632/633/638/641) are in that
    set, so apis_outside_tmf_map_set should be 0."""
    data = build(_sample_components())
    assert data["stats"]["apis_outside_tmf_map_set"] == 0


def test_write_json_writes_pretty_printed_payload(tmp_path: Path) -> None:
    data = build(_sample_components())
    out = tmp_path / "oda_data.json"
    write_json(data, out)

    assert out.exists()
    text = out.read_text(encoding="utf-8")
    assert text.endswith("\n")
    parsed = json.loads(text)
    assert parsed["parser_version"] == __version__
    assert len(parsed["components"]) == 2


def test_write_json_creates_parent_directories(tmp_path: Path) -> None:
    data = build(_sample_components())
    out = tmp_path / "nested" / "subdir" / "oda_data.json"
    write_json(data, out)
    assert out.exists()


def test_write_js_module_creates_es_module_file(tmp_path: Path) -> None:
    data = build(_sample_components())
    out = tmp_path / "oda_data.js"
    write_js_module(data, out)

    assert out.exists()
    content = out.read_text(encoding="utf-8")
    assert "export default ODA_DATA" in content
    assert "const ODA_DATA = " in content
    # Auto-generated banner should be present.
    assert "Auto-generated by tmf-spec-parser oda" in content
