"""
emitter.py — Assemble and write tmf_data.json (and optional JS/TS module).

tmf_data.json schema
--------------------
{
  "generated_at":  "2026-04-17T10:23:00Z",
  "parser_version": "0.1.0",
  "apis": [                          # from API_REGISTRY — stable display metadata
    { "id", "name", "domain", "short", "repo" }
  ],
  "links": [                         # merged: extracted cross-API refs + curated overrides
    { "source", "target", "label" }
  ],
  "patterns": [ ... ],               # from config.PATTERNS (curated)
  "details": {                       # per-API detail, keyed by id
    "TMF641": {
      "specRef":      "TMF641 v4.1.0",
      "description":  "...",
      "entities":     [...],
      "lifecycle":    [...],
      "terminal":     [...],
      "transitions":  [...]
    }
  }
}
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from tmf_spec_parser import __version__
from tmf_spec_parser.config import (
    API_REGISTRY,
    PATTERNS,
    TERMINAL_STATES,
    TRANSITIONS,
)


def _build_links(extracted: dict[str, dict]) -> list[dict[str, str]]:
    """
    Merge auto-extracted cross-API links.
    Deduplicate by (source, target, label).
    """
    seen:  set[tuple[str, str, str]] = set()
    links: list[dict[str, str]]      = []

    for api_id, data in extracted.items():
        for link in data.get("links", []):
            key = (link["source"], link["target"], link["label"])
            if key not in seen:
                seen.add(key)
                links.append(link)

    # Sort for stable output
    links.sort(key=lambda l: (l["source"], l["target"]))
    return links


def _build_details(extracted: dict[str, dict]) -> dict[str, dict]:
    """
    Merge extracted data with curated transitions/terminal states.
    Falls back gracefully if an API wasn't fetched.
    """
    details: dict[str, dict] = {}
    for entry in API_REGISTRY:
        api_id = entry["id"]
        ext    = extracted.get(api_id, {})

        version = ext.get("version", "unknown")
        spec_ref = f"{api_id} v{version}" if version != "unknown" else api_id

        details[api_id] = {
            "specRef":     spec_ref,
            "description": ext.get("description", ""),
            "entities":    ext.get("entities", []),
            "lifecycle":   ext.get("lifecycle", []),
            "terminal":    TERMINAL_STATES.get(api_id, []),
            "transitions": TRANSITIONS.get(api_id, []),
        }

    return details


def build(extracted: dict[str, dict]) -> dict:
    """
    Assemble the full tmf_data structure.

    Parameters
    ----------
    extracted : output of extractor.extract_all()

    Returns
    -------
    Full tmf_data dict ready for JSON serialisation.
    """
    return {
        "generated_at":   datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "parser_version": __version__,
        "apis":           API_REGISTRY,
        "links":          _build_links(extracted),
        "patterns":       PATTERNS,
        "details":        _build_details(extracted),
    }


def write_json(data: dict, output_path: Path, indent: int = 2) -> None:
    """Write tmf_data.json to disk."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(data, indent=indent, ensure_ascii=False),
        encoding="utf-8",
    )


def write_js_module(data: dict, output_path: Path) -> None:
    """
    Write a JavaScript ES module (tmf_data.js) for direct import in React
    without a bundler JSON-import step.

    Usage in App.jsx:
        import TMF_DATA from './tmf_data.js';
    """
    json_str = json.dumps(data, indent=2, ensure_ascii=False)
    js_content = f"// Auto-generated by tmf-spec-parser v{__version__}\n// Do not edit manually — run: tmf-spec-parser generate\n\nexport default {json_str};\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(js_content, encoding="utf-8")


def write_ts_module(data: dict, output_path: Path) -> None:
    """
    Write a TypeScript module with inline type annotation.
    Useful for typed React/TypeScript projects.
    """
    json_str = json.dumps(data, indent=2, ensure_ascii=False)
    ts_content = (
        f"// Auto-generated by tmf-spec-parser v{__version__}\n"
        "// Do not edit manually — run: tmf-spec-parser generate\n\n"
        "export interface TmfData { [key: string]: unknown; }\n\n"
        f"const TMF_DATA: TmfData = {json_str};\n\nexport default TMF_DATA;\n"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(ts_content, encoding="utf-8")


def load_existing(path: Path) -> Optional[dict]:
    """Load an existing tmf_data.json for diffing. Returns None if not found."""
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
