"""
oda_emitter.py — Assemble oda_data.json from extracted ODAC components.

Output schema mirrors the existing tmf_data.json conventions: a flat
structure with `generated_at`, `parser_version`, the data arrays, and
summary stats. See ADR-001 for the full schema definition.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from tmf_spec_parser import __version__
from tmf_spec_parser.config import API_IDS, ODA_SPEC_SOURCE
from tmf_spec_parser.oda_extractor import (
    Component,
    build_links,
    compute_stats,
)


def build(components: list[Component]) -> dict[str, Any]:
    """Assemble the final oda_data.json payload from parsed components."""
    known_apis = set(API_IDS)
    return {
        "generated_at":   datetime.now(timezone.utc)
                          .isoformat(timespec="seconds")
                          .replace("+00:00", "Z"),
        "parser_version": __version__,
        "spec_source":    ODA_SPEC_SOURCE,
        "components":     [c.to_dict() for c in components],
        "links":          build_links(components),
        "stats":          compute_stats(components, known_apis=known_apis),
    }


def write_json(data: dict[str, Any], path: Path) -> None:
    """Write the payload to disk as pretty-printed JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def write_js_module(data: dict[str, Any], path: Path) -> None:
    """Write an ES-module sibling that exports the same data as default.

    Mirrors the convention used by emitter.write_js_module for tmf_data.js
    so that tmf-map can `import ODA_DATA from "./oda_data.js"`.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(data, indent=2)
    content = (
        "// Auto-generated by tmf-spec-parser oda command — do not edit by hand.\n"
        "// Source: " + ODA_SPEC_SOURCE + "\n"
        "// Regenerate with: tmf-spec-parser oda --out ../tmf-map/src/oda_data.json --js\n"
        "const ODA_DATA = " + body + ";\n"
        "export default ODA_DATA;\n"
    )
    path.write_text(content, encoding="utf-8")
